### ISSUE TITLE
Commits to ECMA-262 since 2018-01-01

### ISSUE THREAD

**Issue by devsnek** [devsnek/engine262#65]
- [ ] [Meta: update @alrra/travis-scripts](https://github.com/tc39/ecma262/commit/85ce767c86a1a8ed719fe97e978028bff819d1f2)
- [ ] [Editorial: Update abstract line of JSON.stringify section (#1345)](https://github.com/tc39/ecma262/commit/7acacc524213058a2368b5fa751fac7ea08ba230)
- [ ] [Editorial: Fence non-terminal token for NotCodePoint/CodePoint. (#1337)](https://github.com/tc39/ecma262/commit/2af655fe01b922ea32a64f050de62239046918c2)
- [ ] [Normative: Use array indices instead of integer indices in OrdinaryOwnPropertyKeys (#1242)](https://github.com/tc39/ecma262/commit/9da8fb6ae36899341a3694a4c6af111981b60831)
- [ ] [Editorial: fix typo in section id](https://github.com/tc39/ecma262/commit/f47d5d5b2f455994dd3d4889849a65a64c97ecd7)
- [ ] [Normative: Fix [[OwnPropertyKeys]]() for String exotic objects (#1243)](https://github.com/tc39/ecma262/commit/3e38b659850ec49ccf49f74ec1290795825b956a)
- [ ] [Normative: Add missing return if IteratorComplete to ForIn/OfBodyEvaluation (#1111)](https://github.com/tc39/ecma262/commit/578dd55b4dc727355ec28ffaeecd69196ba8a6d8)
- [ ] [Editorial: fix some Iterator call completions (#1310)](https://github.com/tc39/ecma262/commit/8af002384f9bd5e19496b88d768a73a18d411b32)
- [ ] [Normative: Update Unicode property lists per Unicode v11 (#1218)](https://github.com/tc39/ecma262/commit/691173a72434ccf0ac7cc0104d1eecb6d0c740e7)
- [ ] [Normative: Add missing GetValue() to TemplateLiteral evaluation](https://github.com/tc39/ecma262/commit/44e80585bcf293d1e644d74f13b0462bec5df57f)
- [ ] [Editorial: Add a Return step to ModuleDeclarationEnvironmentSetup (#1266)](https://github.com/tc39/ecma262/commit/f3e73e7225827cade38adb81c85b8c1795874a25)
- [ ] [Editorial: Fix PerformPromiseThen's 'return' step (#1266)](https://github.com/tc39/ecma262/commit/c3a51abf6dc73c7723400319a78426916763b168)
- [ ] [Editorial: _Type_ -> _type_ (#1266)](https://github.com/tc39/ecma262/commit/72df49de86480158e7762a337da02ade7e91febb)
- [ ] [Editorial: semicolon to period (#1266)](https://github.com/tc39/ecma262/commit/4dc4aa5c53edb916ebe7990ec6d6fb9a2136fa35)
- [ ] [Editorial: tweak PerformPromiseThen preamble (#1266)](https://github.com/tc39/ecma262/commit/1a0b732730e4fdcedec16b7e5bea2d6778c6e8ba)
- [ ] [Editorial: tabs to spaces (#1266)](https://github.com/tc39/ecma262/commit/0033dd99b7f3726e1646f7d3b7a531df94a9f0ef)
- [ ] [Editorial: fix type error in 'Valid Chosen Reads' (#1266)](https://github.com/tc39/ecma262/commit/204905e1edc6c9760c30d23e6884fb226777e439)
- [ ] [Editorial: set up the active function in the alg, not the preamble (#1266)](https://github.com/tc39/ecma262/commit/4d0b57c17384756ea6bbee15b84a7b28c11275a3)
- [ ] [Editorial: add ‘!’ to call to StringCreate() (#1266)](https://github.com/tc39/ecma262/commit/b056d9f4502c9f39784d64ceeb35665f6a91997d)
- [ ] [Editorial: tweak 4 constructor preambles (#1266)](https://github.com/tc39/ecma262/commit/ecd1127b4583bcdcf3b67916d626daa58b91c602)
- [ ] [Editorial: tweak two constructor headers (#1266)](https://github.com/tc39/ecma262/commit/2d8b67bb7ab9cde9ce41472597516b68c8b0cb7b)
- [ ] [Editorial: delete space for empty arg list (#1266)](https://github.com/tc39/ecma262/commit/d27f0ec12eec69264d6283d67a85341f90109936)
- [ ] [Editorial: tweak syntax of code unit 'literals' (#1266)](https://github.com/tc39/ecma262/commit/d751daa86fefa6b0bc902f3bb6244d1abc4ee54b)
- [ ] [Editorial: refactor Object.assign (#1266)](https://github.com/tc39/ecma262/commit/fcd2fc9bd2f78c626432394997949a37d64059b1)
- [ ] [Editorial: add 4th argument to Set() call (#1266)](https://github.com/tc39/ecma262/commit/9ce8b389edd469f7c3fa2e1a879a2f07a06dd8f5)
- [ ] [Editorial: fix a couple capitalization errors (#1266)](https://github.com/tc39/ecma262/commit/a35d469f1d9a7bccb9c466fe21255efd40106c82)
- [ ] [Editorial: eliminate "do X and do Y" (#1266)](https://github.com/tc39/ecma262/commit/80e83eb4483f2617219bcd8458ffec59ae4fdbd6)
- [ ] [Editorial: put '?' before some calls to ToUint32() (#1266)](https://github.com/tc39/ecma262/commit/6fa99fade493f65db065eaae043f7ae6289705da)
- [ ] [Editorial: put '!' before more calls to ToInteger() (#1266)](https://github.com/tc39/ecma262/commit/c35da71d302324c6f9387ff9f23cbb557776789f)
- [ ] [Editorial: put '!' before some calls to ToInteger() (#1266)](https://github.com/tc39/ecma262/commit/bfb13de5543b77e03bc084662c63754318710626)
